version: '3.4'

services:
  catalogdb:
    image: mongo


  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile

volumes:
  mongo_data: #volumes are basically data storage
              #that are outside of the containers and
              #exist on the host file system